package com.kick.npl.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

@Immutable
data class CustomColors(
    val primary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val background: Color,
    val surface: Color,
    val surface90: Color,
    val surface99: Color,
    val line: Color,
    val secondaryLine: Color,
    val onBackground0: Color,
    val onBackground40: Color,
    val onBackground60: Color,
    val onBackground70: Color,
    val onSurface0: Color,
    val onSurface40: Color,
    val onSurface60: Color,
    val onSurface70: Color,
    val onSurface90: Color,
    val secondarySurface: Color,
    val secondarySurface40: Color,
    val secondarySurface50: Color,
    val secondarySurface90: Color,
    val onSecondarySurface0: Color,
    val onBackgroundGradation: List<Color>,
    val onSurfaceGradation: List<Color>,
    val onSurface99Gradation: List<Color>,
    val onSurface90Gradation: List<Color>,
    val error: Color,
    // Gradation
    val onBackgroundGradientColor: GradientColor,
    val onSurfaceGradientColor: GradientColor,
    val onSurface99GradientColor: GradientColor,
    val onSurface90GradientColor: GradientColor,
    // Graph
    val graphHigh: Color,
    val graphHigh40: Color,
    val graphHigh80: Color,
    val graphHigh90: Color,
    val graphCaution: Color,
    val graphCaution90: Color,
    val graphSafety: Color,
    val graphSafety10: Color,
    val graphSafety40: Color,
    val graphSafety90: Color,
    val graphSafety99: Color,
    val graphLow: Color,
    val graphLow40: Color
)

val LocalCustomColors = staticCompositionLocalOf {
    CustomColors(
        primary = Color.Unspecified,
        primaryContainer = Color.Unspecified,
        onPrimaryContainer = Color.Unspecified,
        background = Color.Unspecified,
        surface = Color.Unspecified,
        surface90 = Color.Unspecified,
        surface99 = Color.Unspecified,
        line = Color.Unspecified,
        onBackground0 = Color.Unspecified,
        onBackground40 = Color.Unspecified,
        onBackground60 = Color.Unspecified,
        onBackground70 = Color.Unspecified,
        onSurface0 = Color.Unspecified,
        onSurface40 = Color.Unspecified,
        onSurface60 = Color.Unspecified,
        onSurface70 = Color.Unspecified,
        onSurface90 = Color.Unspecified,
        secondaryLine = Color.Unspecified,
        secondarySurface = Color.Unspecified,
        secondarySurface40 = Color.Unspecified,
        secondarySurface50 = Color.Unspecified,
        secondarySurface90 = Color.Unspecified,
        onSecondarySurface0 = Color.Unspecified,
        onBackgroundGradation = emptyList(),
        onSurfaceGradation = emptyList(),
        onSurface99Gradation = emptyList(),
        onSurface90Gradation = emptyList(),
        error = Color.Unspecified,
        // Gradation
        onBackgroundGradientColor = GradientColor.Unspecified,
        onSurfaceGradientColor = GradientColor.Unspecified,
        onSurface99GradientColor = GradientColor.Unspecified,
        onSurface90GradientColor = GradientColor.Unspecified,
        // Graph
        graphHigh = Color.Unspecified,
        graphHigh40 = Color.Unspecified,
        graphHigh80 = Color.Unspecified,
        graphHigh90 = Color.Unspecified,
        graphCaution = Color.Unspecified,
        graphCaution90 = Color.Unspecified,
        graphSafety = Color.Unspecified,
        graphSafety10 = Color.Unspecified,
        graphSafety40 = Color.Unspecified,
        graphSafety90 = Color.Unspecified,
        graphSafety99 = Color.Unspecified,
        graphLow = Color.Unspecified,
        graphLow40 = Color.Unspecified,
    )
}